name: CS3D
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - cvxpy
  - pip:
    - obspy
    - matplotlib
    - plotly
    - tqdm
