import numpy as np
import torch
from scipy.interpolate import RegularGridInterpolator

def generate_simple_indices_3d(T: int, H: int, W: int, n: int, nt: int):
    """generate the indices of the main spectrum for a video with given dimensions and sampling intervals.

    Args:
        T (int): The number of frames in the video
        H (int): The height of the video
        W (int): The width of the video
        n (int): The sampling interval for height and width
        nt (int): The sampling interval for time
    Returns:
        np.ndarray: The 3D indices, shape (N, 3)
    """
    shape = (T//nt, H//n, W//n)
    indices = np.indices(shape)
    indices_3d = indices.transpose(1, 2, 3, 0).reshape(-1, 3)
    return indices_3d

def normalize(video: np.ndarray):
    return video/np.max(abs(video))


def gene_mask(video: np.ndarray, H: int, W: int, K: int, sample_ratio: float = 0.01, mask_type: str = 'float'):
    """ 
    generate the observation and the corresponding positions for a video, with a given sampling ratio and mask type.
    because the used data are usually at the regular grid, we can directly sample the pixel values at the masked positions. 
    However, for the real data, the positions of the observations may not be at the regular grid, 
    so we can use bilinear interpolation to get the observation values at the sampled positions. 
    mask_type can be 'int' or 'float'. If 'int', the mask will be binary, 
    and the observation will be the pixel values at the masked positions. 
    If 'float', the mask will be generated by random sampling, 
    and the observation will be obtained by bilinear interpolation at the sampled positions.
    Args:
        video (np.ndarray): the input video, shape (T, H, W)
        H (int): the height of the video
        W (int): the width of the video 
        K (int): the number of observations for testing
        sample_ratio (float): the sampling ratio of H*W pixels for computing
        mask_type (str): the type of the mask, can be 'int' or 'float'
    Returns:
        ob (np.ndarray): the observation, shape (T, K)
        ob_pos (np.ndarray): the positions of the observations, shape (K, 2)
        test_pos (np.ndarray): the positions of the test points, shape (K, 2)
    """
    L = H*W
    sample_num = int(L*sample_ratio)
    if mask_type == 'int':
        mask_per_frame = np.hstack([np.zeros(L - sample_num), np.ones(sample_num)])
        np.random.shuffle(mask_per_frame)
        mask_per_frame = mask_per_frame.reshape(H,W)
        ob_pos = np.argwhere(mask_per_frame == 1)
        ob = video[:,ob_pos[:,0],ob_pos[:,1]]
    elif mask_type == 'float':
        x = np.random.uniform(0, W-1, size=sample_num + K)
        y = np.random.uniform(0, H-1, size=sample_num + K)
        all_pos = np.column_stack((x, y))
        ob_pos,test_pos = all_pos[:-K],all_pos[-K:]
        T = video.shape[0]
        for i in range(T):
            h_coords,w_coords = np.arange(H),np.arange(W)
            interp_func = RegularGridInterpolator(
                (h_coords, w_coords),
                np.zeros((H,W)))
            ob = np.zeros((T, sample_num))
            for t in range(T):
                interp_func.values = video[t,:,:]
                ob[t, :] = interp_func(ob_pos, method='linear')
                
    return ob, ob_pos, test_pos

def shuffle(data: np.ndarray, pos: np.ndarray, sta_info: np.ndarray, keep: int):
    """
        shuffle the data, positions and station information, and split the data into two parts: one for computing and one for testing.
    Args:
        data (np.ndarray): the input data, shape (T, K)
        pos (np.ndarray): the positions of the data, shape (K, 2)
        sta_info (np.ndarray): the station information, shape (K, ...)
        keep (int): the number of samples to keep for computing, the rest will be used for testing
    Returns:
        ob (np.ndarray): the data for computing, shape (T, keep)
        test_sta (np.ndarray): the data for testing, shape (T, K-keep)
        full_pos (np.ndarray): the full positions, shape (K, 2)
        sta_info (np.ndarray): the full station information, shape (K, ...)
    """
    K = data.shape[1]
    combined_coords = pos.copy() 
    random_indices = np.random.permutation(K)
    shuffled_data = data[:, random_indices]
    shuffled_coords = combined_coords[random_indices, :]
    shuffled_sta_info = sta_info[random_indices, :]
    return shuffled_data[:, :keep], shuffled_data[:, keep:], shuffled_coords, shuffled_sta_info


def smooth_function(video1, video2, window_type: str = 'linear'):
    """smooth the transition between two videos using a specified window function.
        Issue: Boundary discontinuities during segment-wise seismic data restoration.
        Solution: Implemented Overlap-Add (OLA) blending with a linear ramp (cross-fade) to ensure
        continuity between processed windows.
    Args:
        video1 (np.ndarray): the first video, shape (T, H, W)
        video2 (np.ndarray): the second video, shape (T, H, W)
        window_type (str, optional): the type of window function to use. Defaults to 'linear'.

    Raises:
        ValueError: if the window_type is not supported
        
    Returns:
        result: the smoothed video, shape (T, H, W)
    """
    T, H, W = video1.shape
    if window_type == 'linear':
        weights = np.linspace(0, 1, T)
    elif window_type == 'hann':
        n = np.arange(T)
        weights = 0.5 * (1 - np.cos(2 * np.pi * n / (T - 1)))
    elif window_type == 'hamming':
        n = np.arange(T)
        weights = 0.54 - 0.46 * np.cos(2 * np.pi * n / (T - 1))
    elif window_type == 'blackman':
        n = np.arange(T)
        weights = (0.42 - 0.5 * np.cos(2 * np.pi * n / (T - 1)) + 
                  0.08 * np.cos(4 * np.pi * n / (T - 1)))
    else:
        raise ValueError("window_type must be 'linear', 'hann', 'hamming', or 'blackman'")

    weights = torch.as_tensor(weights, device=video1.device, dtype=video1.dtype)
    weights_3d = weights[:, None, None]
    reverse_weights_3d = weights.flip(0)[:, None, None]
    result = (weights_3d * video1 + reverse_weights_3d * video2)
    
    return result 

def joint(video_list: list, overlap_len: int, smooth_function=smooth_function):
    """joint a list of videos into a long video,
    with a specified overlap length for smoothing the transition between consecutive videos.

    Args:
        video_list (list): A list of videos to be joined, each with shape (T, H, W)
        overlap_len (int): The length of the overlapping region between consecutive videos

    Returns:
        np.ndarray: The joined video with shape (T, H, W)
    """
    pieces = []
    pieces.append(video_list[0][:-overlap_len])
    
    for i in range(len(video_list) - 1):
        smooth_seg = smooth_function(video_list[i][-overlap_len:], video_list[i+1][:overlap_len])
        pieces.append(smooth_seg)

        if i + 1 == len(video_list) - 1:
            pieces.append(video_list[i+1][overlap_len:])
        else:
            pieces.append(video_list[i+1][overlap_len:-overlap_len])
    
    return torch.concatenate(pieces, dim=0).cpu().numpy()

def get_sta_pos(sta_info: np.ndarray, selected_sta_info: np.ndarray, allpoints: np.ndarray, full_pos: np.ndarray):
    """
        get the positions of the selected stations based on their information.
    Args:
        sta_info (np.ndarray): the station information, shape (K, ...)
        selected_sta_info (np.ndarray): the information of the selected stations, shape (M, ...)
        allpoints (np.ndarray): the coordinates of all stations, shape (K, 2)
        full_pos (np.ndarray): the full positions of all stations, shape (K, 2) 
    Returns:
        ob (np.ndarray): the observation, shape (T, K)
        test_sta (np.ndarray): the data for testing, shape (T, M)
        full_pos (np.ndarray): the full positions, shape (K, 2)
        sta_info (np.ndarray): the full station information, shape (K, ...) 
    """
    test_idx = []
    for row in selected_sta_info:
        match_indices = np.where((sta_info == row).all(axis=1))[0]
        if len(match_indices) > 0:
            test_idx.append(match_indices[0])
    all_indices = np.arange(sta_info.shape[0])
    test_idx = np.array(test_idx)
    keep_idx = np.setdiff1d(all_indices, test_idx)
    new_order = np.concatenate([keep_idx, test_idx])
    K = len(keep_idx)
    ob, test_sta = allpoints[:,new_order[:K]], allpoints[:, new_order[K:]]
    full_pos = full_pos[new_order]
    sta_info = sta_info[new_order]
    
    return ob, test_sta, full_pos, sta_info